import { useMemo } from 'react';

import { getNavigationBarHeight } from 'react-native-android-navbar-height';
import useDimensions from 'use-dimensions';

import { IS_ANDROID, IS_IOS } from '@src/configs/constants';
import {
    fontScale,
    horizontalScale,
    radiusScale,
    verticalScale,
} from '@src/utils/sizeScaling';
import {
    getStatusBarHeight,
    isIPhoneXAndAfterX,
} from '@src/utils/sizeScaling/iphoneScreenSizeHelper';

const useDimens = (type: 'screen' | 'window' = 'screen') => {
    const { screen, window } = useDimensions();
    const softMenuBarHeight = getNavigationBarHeight();
    if(IS_IOS) {
        console.log('useDimens: getStatusBarHeight is', getStatusBarHeight);
    }
    const statusBarHeight = getStatusBarHeight ? getStatusBarHeight() : 0; // Guard to debug

    let width = window.width;
    let height = window.height + (IS_ANDROID ? statusBarHeight : 0);

    if (type === 'screen') {
        width = screen.width;
        height = screen.height;
    }

    const appDimens = useMemo(() => ({
        W_0: 0,
        W_1: horizontalScale(1, width),
        W_2: horizontalScale(2, width),
        W_3: horizontalScale(3, width),
        W_4: horizontalScale(4, width),
        W_5: horizontalScale(5, width),
        W_6: horizontalScale(6, width),
        W_7: horizontalScale(7, width),
        W_8: horizontalScale(8, width),
        W_9: horizontalScale(9, width),
        W_10: horizontalScale(10, width),
        W_11: horizontalScale(11, width),
        W_12: horizontalScale(12, width),
        W_13: horizontalScale(13, width),
        W_14: horizontalScale(14, width),
        W_15: horizontalScale(15, width),
        W_16: horizontalScale(16, width),
        W_17: horizontalScale(17, width),
        W_18: horizontalScale(18, width),
        W_19: horizontalScale(19, width),
        W_20: horizontalScale(20, width),
        W_21: horizontalScale(21, width),
        W_22: horizontalScale(22, width),
        W_23: horizontalScale(23, width),
        W_24: horizontalScale(24, width),
        W_25: horizontalScale(25, width),
        W_26: horizontalScale(26, width),
        W_27: horizontalScale(27, width),
        W_28: horizontalScale(28, width),
        W_29: horizontalScale(29, width),
        W_30: horizontalScale(30, width),
        W_31: horizontalScale(31, width),
        W_32: horizontalScale(32, width),
        W_33: horizontalScale(33, width),
        W_34: horizontalScale(34, width),
        W_35: horizontalScale(35, width),
        W_36: horizontalScale(36, width),
        W_37: horizontalScale(37, width),
        W_38: horizontalScale(38, width),
        W_39: horizontalScale(39, width),
        W_40: horizontalScale(40, width),
        W_41: horizontalScale(41, width),
        W_42: horizontalScale(42, width),
        W_43: horizontalScale(43, width),
        W_44: horizontalScale(44, width),
        W_45: horizontalScale(45, width),
        W_46: horizontalScale(46, width),
        W_47: horizontalScale(47, width),
        W_48: horizontalScale(48, width),
        W_49: horizontalScale(49, width),
        W_50: horizontalScale(50, width),
        W_51: horizontalScale(51, width),
        W_52: horizontalScale(52, width),
        W_53: horizontalScale(53, width),
        W_54: horizontalScale(54, width),
        W_55: horizontalScale(55, width),
        W_56: horizontalScale(56, width),
        W_57: horizontalScale(57, width),
        W_58: horizontalScale(58, width),
        W_59: horizontalScale(59, width),
        W_60: horizontalScale(60, width),
        W_61: horizontalScale(61, width),
        W_62: horizontalScale(62, width),
        W_63: horizontalScale(63, width),
        W_64: horizontalScale(64, width),
        W_65: horizontalScale(65, width),
        W_66: horizontalScale(66, width),
        W_67: horizontalScale(67, width),
        W_68: horizontalScale(68, width),
        W_69: horizontalScale(69, width),
        W_70: horizontalScale(70, width),
        W_71: horizontalScale(71, width),
        W_72: horizontalScale(72, width),
        W_73: horizontalScale(73, width),
        W_74: horizontalScale(74, width),
        W_75: horizontalScale(75, width),
        W_76: horizontalScale(76, width),
        W_77: horizontalScale(77, width),
        W_78: horizontalScale(78, width),
        W_79: horizontalScale(79, width),
        W_80: horizontalScale(80, width),
        W_81: horizontalScale(81, width),
        W_82: horizontalScale(82, width),
        W_83: horizontalScale(83, width),
        W_84: horizontalScale(84, width),
        W_85: horizontalScale(85, width),
        W_86: horizontalScale(86, width),
        W_87: horizontalScale(87, width),
        W_88: horizontalScale(88, width),
        W_89: horizontalScale(89, width),
        W_90: horizontalScale(90, width),
        W_91: horizontalScale(91, width),
        W_92: horizontalScale(92, width),
        W_93: horizontalScale(93, width),
        W_94: horizontalScale(94, width),
        W_95: horizontalScale(95, width),
        W_96: horizontalScale(96, width),
        W_97: horizontalScale(97, width),
        W_98: horizontalScale(98, width),
        W_99: horizontalScale(99, width),
        W_100: horizontalScale(100, width),
        W_110: horizontalScale(110, width),
        W_118: horizontalScale(118, width),
        W_120: horizontalScale(120, width),
        W_124: horizontalScale(124, width),
        W_127: horizontalScale(127, width),
        W_128: horizontalScale(128, width),
        W_130: horizontalScale(130, width),
        W_138: horizontalScale(138, width),
        W_140: horizontalScale(140, width),
        W_144: horizontalScale(144, width),
        W_150: horizontalScale(150, width),
        W_155: horizontalScale(155, width),
        W_160: horizontalScale(160, width),
        W_172: horizontalScale(172, width),
        W_173: horizontalScale(173, width),
        W_180: horizontalScale(180, width),
        W_186: horizontalScale(186, width),
        W_192: horizontalScale(192, width),
        W_199: horizontalScale(199, width),
        W_200: horizontalScale(200, width),
        W_206: horizontalScale(206, width),
        W_216: horizontalScale(216, width),
        W_220: horizontalScale(220, width),
        W_230: horizontalScale(230, width),
        W_241: horizontalScale(241, width),
        W_248: horizontalScale(248, width),
        W_268: horizontalScale(268, width),
        W_280: horizontalScale(280, width),
        W_290: horizontalScale(290, width),
        W_297: horizontalScale(297, width),
        W_336: horizontalScale(336, width),
        W_338: horizontalScale(338, width),
        W_350: horizontalScale(350, width),
        W_360: horizontalScale(360, width),
        W_391: horizontalScale(391, width),
        W_999: horizontalScale(999, width),

        H_0: 0,
        H_1: verticalScale(1, height),
        H_2: verticalScale(2, height),
        H_3: verticalScale(3, height),
        H_4: verticalScale(4, height),
        H_5: verticalScale(5, height),
        H_6: verticalScale(6, height),
        H_7: verticalScale(7, height),
        H_8: verticalScale(8, height),
        H_9: verticalScale(9, height),
        H_10: verticalScale(10, height),
        H_11: verticalScale(11, height),
        H_12: verticalScale(12, height),
        H_13: verticalScale(13, height),
        H_14: verticalScale(14, height),
        H_15: verticalScale(15, height),
        H_16: verticalScale(16, height),
        H_17: verticalScale(17, height),
        H_18: verticalScale(18, height),
        H_19: verticalScale(19, height),
        H_20: verticalScale(20, height),
        H_21: verticalScale(21, height),
        H_22: verticalScale(22, height),
        H_23: verticalScale(23, height),
        H_24: verticalScale(24, height),
        H_25: verticalScale(25, height),
        H_26: verticalScale(26, height),
        H_27: verticalScale(27, height),
        H_28: verticalScale(28, height),
        H_29: verticalScale(29, height),
        H_30: verticalScale(30, height),
        H_31: verticalScale(31, height),
        H_32: verticalScale(32, height),
        H_33: verticalScale(33, height),
        H_34: verticalScale(34, height),
        H_35: verticalScale(35, height),
        H_36: verticalScale(36, height),
        H_37: verticalScale(37, height),
        H_38: verticalScale(38, height),
        H_39: verticalScale(39, height),
        H_40: verticalScale(40, height),
        H_41: verticalScale(41, height),
        H_42: verticalScale(42, height),
        H_43: verticalScale(43, height),
        H_44: verticalScale(44, height),
        H_45: verticalScale(45, height),
        H_46: verticalScale(46, height),
        H_47: verticalScale(47, height),
        H_48: verticalScale(48, height),
        H_49: verticalScale(49, height),
        H_50: verticalScale(50, height),
        H_51: verticalScale(51, height),
        H_52: verticalScale(52, height),
        H_53: verticalScale(53, height),
        H_54: verticalScale(54, height),
        H_55: verticalScale(55, height),
        H_56: verticalScale(56, height),
        H_57: verticalScale(57, height),
        H_58: verticalScale(58, height),
        H_59: verticalScale(59, height),
        H_60: verticalScale(60, height),
        H_61: verticalScale(61, height),
        H_62: verticalScale(62, height),
        H_63: verticalScale(63, height),
        H_64: verticalScale(64, height),
        H_65: verticalScale(65, height),
        H_66: verticalScale(66, height),
        H_67: verticalScale(67, height),
        H_68: verticalScale(68, height),
        H_69: verticalScale(69, height),
        H_70: verticalScale(70, height),
        H_71: verticalScale(71, height),
        H_72: verticalScale(72, height),
        H_73: verticalScale(73, height),
        H_74: verticalScale(74, height),
        H_75: verticalScale(75, height),
        H_76: verticalScale(76, height),
        H_77: verticalScale(77, height),
        H_78: verticalScale(78, height),
        H_79: verticalScale(79, height),
        H_80: verticalScale(80, height),
        H_81: verticalScale(81, height),
        H_82: verticalScale(82, height),
        H_83: verticalScale(83, height),
        H_84: verticalScale(84, height),
        H_85: verticalScale(85, height),
        H_86: verticalScale(86, height),
        H_87: verticalScale(87, height),
        H_88: verticalScale(88, height),
        H_89: verticalScale(89, height),
        H_90: verticalScale(90, height),
        H_91: verticalScale(91, height),
        H_92: verticalScale(92, height),
        H_93: verticalScale(93, height),
        H_94: verticalScale(94, height),
        H_95: verticalScale(95, height),
        H_96: verticalScale(96, height),
        H_97: verticalScale(97, height),
        H_98: verticalScale(98, height),
        H_99: verticalScale(99, height),
        H_100: verticalScale(100, height),
        H_106: verticalScale(106, height),
        H_110: verticalScale(110, height),
        H_120: verticalScale(120, height),
        H_124: verticalScale(124, height),
        H_127: verticalScale(127, height),
        H_128: verticalScale(128, height),
        H_130: verticalScale(130, height),
        H_138: verticalScale(138, height),
        H_140: verticalScale(140, height),
        H_144: verticalScale(144, height),
        H_150: verticalScale(150, height),
        H_160: verticalScale(160, height),
        H_172: verticalScale(172, height),
        H_180: verticalScale(180, height),
        H_186: verticalScale(186, height),
        H_192: verticalScale(192, height),
        H_199: verticalScale(199, height),
        H_200: verticalScale(200, height),
        H_206: verticalScale(206, height),
        H_210: verticalScale(210, height),
        H_216: verticalScale(216, height),
        H_220: verticalScale(220, height),
        H_248: verticalScale(248, height),
        H_275: verticalScale(275, height),
        H_297: verticalScale(297, height),
        H_310: verticalScale(310, height),
        H_336: verticalScale(336, height),
        H_338: verticalScale(338, height),
        H_353: verticalScale(353, height),
        H_360: verticalScale(360, height),
        H_385: verticalScale(385, height),
        H_391: verticalScale(391, width),
        H_999: verticalScale(999, width),

        FONT_30: fontScale(30, width, height),
        FONT_28: fontScale(28, width, height),
        FONT_26: fontScale(26, width, height),
        FONT_24: fontScale(24, width, height),
        FONT_23: fontScale(23, width, height),
        FONT_22: fontScale(22, width, height),
        FONT_21: fontScale(21, width, height),
        FONT_20: fontScale(20, width, height),
        FONT_18: fontScale(18, width, height),
        FONT_16: fontScale(16, width, height),
        FONT_15: fontScale(15, width, height),
        FONT_14: fontScale(14, width, height),
        FONT_13: fontScale(13, width, height),
        FONT_12: fontScale(12, width, height),
        FONT_11: fontScale(11, width, height),
        FONT_10: fontScale(10, width, height),
        FONT_9: fontScale(9, width, height),
        FONT_8: fontScale(8, width, height),

        RADIUS_2: radiusScale(2, width, height),
        RADIUS_3: radiusScale(3, width, height),
        RADIUS_4: radiusScale(4, width, height),
        RADIUS_6: radiusScale(6, width, height),
        RADIUS_8: radiusScale(8, width, height),
        RADIUS_10: radiusScale(10, width, height),
        RADIUS_12: radiusScale(12, width, height),
        RADIUS_14: radiusScale(14, width, height),
        RADIUS_16: radiusScale(16, width, height),
        RADIUS_18: radiusScale(18, width, height),
        RADIUS_20: radiusScale(20, width, height),
        RADIUS_22: radiusScale(22, width, height),
        RADIUS_24: radiusScale(24, width, height),
        RADIUS_26: radiusScale(26, width, height),
        RADIUS_28: radiusScale(28, width, height),
        RADIUS_30: radiusScale(30, width, height),
        RADIUS_32: radiusScale(32, width, height),
        RADIUS_38: radiusScale(38, width, height),
        RADIUS_45: radiusScale(45, width, height),
        RADIUS_248: radiusScale(248, width, height),
        RADIUS_70: radiusScale(70, width, height),
        RADIUS_80: radiusScale(80, width, height),
        RADIUS_999: radiusScale(999, width, height),

        SOFT_MENU_BAR_HEIGHT: softMenuBarHeight,
        STATUS_BAR_HEIGHT: statusBarHeight,
        SCREEN_WIDTH: width,
        SCREEN_HEIGHT: height, // height màn hình tính cả status bar và sorf navigation bar
        SCREEN_HEIGHT_NO_NAVIGATION_BAR: height - softMenuBarHeight, // height màn hình tính cả status bar và KHÔNG TÍNH sorf navigation bar
        SCREEN_HEIGHT_AVAILABLE: height - softMenuBarHeight - statusBarHeight, // height màn hình KHÔNG TÍNH status bar và sorf navigation bar
        COMMON_BOTTOM_PADDING: IS_ANDROID || !isIPhoneXAndAfterX() ? verticalScale(16, height) : verticalScale(21, height),
        COMMON_HEADER_PADDING_EXTRA: verticalScale(16, height),
        COMMON_HEADER_PADDING: verticalScale(statusBarHeight, height) + verticalScale(16, height), // + COMMON_HEADER_PADDING_EXTRA
        TAB_BAR_BOTTOM_PADDING: IS_ANDROID || !isIPhoneXAndAfterX() ? verticalScale(4, height) : verticalScale(21, height),
        HEADER_BORDER_RADIUS: verticalScale(8, height),
        DEFAULT_HIT_SLOP: {
            left: verticalScale(12, height),
            top: verticalScale(12, height),
            right: verticalScale(12, height),
            bottom: verticalScale(12, height),
        },
        DEFAULT_HIT_SLOP_SMALL: {
            left: verticalScale(4, height),
            top: verticalScale(4, height),
            right: verticalScale(4, height),
            bottom: verticalScale(4, height),
        }
    }), [height, softMenuBarHeight, statusBarHeight, width]);

    return appDimens;
};

export default useDimens;

export type DimensType = ReturnType<typeof useDimens>;
